name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and Upload CLI Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build CLI binaries
        run: deno task build:cli

      - name: Generate checksums
        working-directory: dist
        run: sha256sum * > SHA256SUMS

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/jphw-*
            dist/SHA256SUMS
